name: Docker Build and Push CI

on:
  push:
    paths:
      - 'Docker/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      -
        name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/netbox:latest,${{ secrets.DOCKERHUB_USERNAME }}/netbox:v1
          file: Docker/Hosts/netbox/Dockerfile
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/netbox
          readme-filepath: Docker/Hosts/netbox/netbox.README.md