name: Docker Build and Publish CI

on:
  push:
    paths:
      - 'Docker/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}
      -
        name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: nanafox/netbox:latest,nanafox/netbox:v1
          file: Docker/Hosts/netbox/netbox.Dockerfile
