name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  login:
    runs-on: ubuntu-latest
     - uses: mr-smithers-excellent/docker-build-push@v6
    name: Build & push Docker image
    with:
      image: nanafox/netbox
      tags: v1, latest
      registry: docker.io
      dockerfile: Docker/Hosts/netbox/netbox.Dockerfile
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}